# Generated by Django 4.1.2 on 2022-10-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restful", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="名称")),
                ("age", models.IntegerField(verbose_name="年龄")),
            ],
            options={
                "verbose_name": "作者",
                "verbose_name_plural": "作者",
                "db_table": "Author",
            },
        ),
        migrations.CreateModel(
            name="Publish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="名称")),
                ("addr", models.CharField(max_length=32, verbose_name="地址")),
            ],
            options={
                "verbose_name": "出版",
                "verbose_name_plural": "出版",
                "db_table": "Publish",
            },
        ),
    ]
