# Generated by Django 3.0.5 on 2022-10-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20221019_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(blank=True, default='123', max_length=30, null=True, verbose_name='测试字段'),
        ),
    ]
