# Generated by Django 3.0.5 on 2022-10-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20221019_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='身份证号')),
                ('address', models.CharField(max_length=100, verbose_name='住址')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
            options={
                'verbose_name_plural': '身份证表',
                'db_table': 'idcard',
            },
        ),
    ]
